# Generated by Django 5.0 on 2024-01-04 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='admin',
            table='ttmadmin_table',
        ),
    ]
