# Generated by Django 5.0 on 2024-02-08 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_rename_phno_register_phonenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='password',
            new_name='pwd',
        ),
    ]
