# Generated by Django 5.0 on 2024-02-08 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_rename_password_register_pwd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='pwd',
            new_name='password',
        ),
    ]
